### ISSUE TITLE
[Forge 1.18.2] Failed to create mod instance. ModID: reaping, class io.github.jamalam360.reaping.forge.ReapingForge

### ISSUE THREAD

**Issue by pavog** [JamCoreModding/reaping-old#2]
Hi, I use the latest version ([V2.1.0 [1.18.2 / Forge]](https://www.curseforge.com/minecraft/mc-mods/reaping/files/3788325)) for my Forge 1.18.2 server. I installed the newest version of architectury api (4.4.60).

I get this error on startup:

```
[13May2022 11:07:35.027] [modloading-worker-0/INFO] [io.github.jamalam360.reaping.ReapingMod/]: [Reaping] Initializing Reaping Mod...
--
9 | [13May2022 11:07:35.043] [modloading-worker-0/ERROR] [net.minecraftforge.fml.javafmlmod.FMLModContainer/LOADING]: Failed to create mod instance. ModID: reaping, class io.github.jamalam360.reaping.forge.ReapingForge
10 | java.lang.reflect.InvocationTargetException: null
11 | at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
12 | at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?]
13 | at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
14 | at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
15 | at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?]
16 | at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:67) ~[javafmllanguage-1.18.2-40.1.0.jar%2346!/:?]
17 | at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:106) ~[fmlcore-1.18.2-40.1.0.jar%2345!/:?]
18 | at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) [?:?]
19 | at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) [?:?]
20 | at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) [?:?]
21 | at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) [?:?]
22 | at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) [?:?]
23 | at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) [?:?]
24 | at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) [?:?]
25 | Caused by: java.lang.NoClassDefFoundError: me/shedaniel/autoconfig/ConfigData
26 | at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
27 | at java.lang.ClassLoader.defineClass(ClassLoader.java:1012) ~[?:?]
28 | at cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:116) ~[securejarhandler-1.0.3.jar:?]
29 | at cpw.mods.cl.ModuleClassLoader.lambda$findClass$16(ModuleClassLoader.java:216) ~[securejarhandler-1.0.3.jar:?]
30 | at cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:226) ~[securejarhandler-1.0.3.jar:?]
31 | at cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:216) ~[securejarhandler-1.0.3.jar:?]
32 | at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:132) ~[securejarhandler-1.0.3.jar:?]
33 | at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
34 | at io.github.jamalam360.reaping.ReapingMod.init(ReapingMod.java:35) ~[reaping-2.1.0+forge.jar%2341!/:?]
35 | at io.github.jamalam360.reaping.forge.ReapingForge.<init>(ReapingForge.java:16) ~[reaping-2.1.0+forge.jar%2341!/:?]
36 | ... 14 more
37 | Caused by: java.lang.ClassNotFoundException: me.shedaniel.autoconfig.ConfigData
38 | at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
39 | at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
40 | at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:134) ~[securejarhandler-1.0.3.jar:?]
41 | at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
42 | at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:134) ~[securejarhandler-1.0.3.jar:?]
43 | at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
44 | at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
45 | at java.lang.ClassLoader.defineClass(ClassLoader.java:1012) ~[?:?]
46 | at cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:116) ~[securejarhandler-1.0.3.jar:?]
47 | at cpw.mods.cl.ModuleClassLoader.lambda$findClass$16(ModuleClassLoader.java:216) ~[securejarhandler-1.0.3.jar:?]
48 | at cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:226) ~[securejarhandler-1.0.3.jar:?]
49 | at cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:216) ~[securejarhandler-1.0.3.jar:?]
50 | at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:132) ~[securejarhandler-1.0.3.jar:?]
51 | at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
52 | at io.github.jamalam360.reaping.ReapingMod.init(ReapingMod.java:35) ~[reaping-2.1.0+forge.jar%2341!/:?]
53 | at io.github.jamalam360.reaping.forge.ReapingForge.<init>(ReapingForge.java:16) ~[reaping-2.1.0+forge.jar%2341!/:?]
54 | ... 14 more
```

Full server log:
https://mclo.gs/bnvhFCn

**Comment by Jamalam360** [comment]
Do you have cloth config installed?

**Comment by pavog** [comment]
oh no, I forgot that.
Sorry, now it's fixed.


Maybe you can add a check for this or something that prints out an understandable error message?
So that I / users can easily understand that ^^

**Comment by Jamalam360** [comment]
Yep, forgot that

#3
